// This is the main file for the Netlify Build plugin qworum.
// Please read the comments to learn more about the Netlify Build plugin syntax.
// Find more information in the Netlify documentation.

// environment variables
import process from 'node:process';

// http client
// import got from 'got';

import { verifyWebsiteEntitlement } from "./modules/website-entitlement-verifier.mjs";


/* eslint-disable no-unused-vars */
// The plugin main logic uses `on...` event handlers that are triggered on
// each new Netlify Build.
// Anything can be done inside those event handlers.
// Information about the current build are passed as arguments. The build
// configuration file and some core utilities are also available.
export const onPreBuild = async function ({
  // Whole configuration file. For example, content of `netlify.toml`
  netlifyConfig,

  // Users can pass configuration inputs to any plugin in their Netlify
  // configuration file.
  // For example:
  //
  //   [[plugins]]
  //   package = "netlify-plugin-qworum"
  //     [plugins.inputs]
  //     foo = "bar"
  inputs,

  // `onError` event handlers receive the error instance as argument
  error,

  // Build constants
  constants: {
    // Path to the Netlify configuration file. `undefined` if none was used
    CONFIG_PATH,

    // Directory that contains the deploy-ready HTML files and assets
    // generated by the build. Its value is always defined, but the target
    // might not have been created yet.
    PUBLISH_DIR,

    // The directory where function source code lives.
    // `undefined` if not specified by the user.
    FUNCTIONS_SRC,

    // The directory where built serverless functions are placed before
    // deployment. Its value is always defined, but the target might not have
    // been created yet.
    FUNCTIONS_DIST,

    // Boolean indicating whether the build was run locally (Netlify CLI) or
    // in the production CI
    IS_LOCAL,

    // Version of Netlify Build as a `major.minor.patch` string
    NETLIFY_BUILD_VERSION,

    // The Netlify Site ID
    SITE_ID,
  },

  // Core utilities
  utils: {
    // Utility to report errors.
    // See https://github.com/netlify/build#error-reporting
    build,

    // Utility to display information in the deploy summary.
    // See https://github.com/netlify/build#logging
    status,

    // Utility for caching files.
    // See https://github.com/netlify/build/blob/master/packages/cache-utils#readme
    cache,

    // Utility for running commands.
    // See https://github.com/netlify/build/blob/master/packages/run-utils#readme
    run,

    // Utility for dealing with modified, created, deleted files since a git commit.
    // See https://github.com/netlify/build/blob/master/packages/git-utils#readme
    git,

    // Utility for handling Netlify Functions.
    // See https://github.com/netlify/build/tree/master/packages/functions-utils#readme
    functions,
  },
}) {
  // verify website entitlement
  try {
    const siteUrl = process.env.URL;
    // console.log(`site url: ${siteUrl}`);

    const siteEnabled = await verifyWebsiteEntitlement(siteUrl);

    if (!siteEnabled) {
      throw new Error(`Qworum is not enabled for ${siteUrl}.`);
    }

  } catch (error) {
    // Report a user error
    build.failBuild(`Read this to enable Qworum for your website: "https://qworum.net/en/#entitlement".`, { error })
  }

  // Display success information
  status.show({ summary: 'Build can proceed, Qworum is already enabled for this website.' })
}

// Other available event handlers
/*

// Before build commands are executed
export const onPreBuild = function() {
  console.log("Hello world from onPreBuild event!");
}

// Build commands are executed
export const onBuild = function () {}

// After Build commands are executed
export const onPostBuild = function () {}

// Runs on build success
export const onSuccess = function () {}

// Runs on build error
export const onError = function () {}

// Runs on build error or success
export const onEnd = function () {}

*/




/* netlify-plugin-sitemap's index.js */

// const { env } = require('process')

// const makeSitemap = require('./make_sitemap')

// const getInputsDir = ({ inputs }) => inputs.dir || inputs.distPath || inputs.buildDir

// const getBuildDir = ({ inputs, constants }) => {
//   // Backwards compat... Correct opt is buildDir
//   const buildDir = getInputsDir({ inputs }) || constants.PUBLISH_DIR
//   // constants.PUBLISH_DIR is always an absolute path
//   if (buildDir === constants.PUBLISH_DIR) {
//     return buildDir
//   }
//   // remove leading / to treat the dir a a relative one
//   const trimmedBuildDir = buildDir.startsWith('/') ? buildDir.slice(1) : buildDir
//   return trimmedBuildDir || '.'
// }

// module.exports = {
//   onPostBuild: async ({ constants, inputs, utils }) => {
//     const baseUrl = inputs.baseUrl || env.NETLIFY_PLUGIN_SITEMAP_BASEURL || env.URL
//     const urlPrefix = inputs.urlPrefix || env.NETLIFY_PLUGIN_SITEMAP_URL_PREFIX || null
//     const buildDir = getBuildDir({ inputs, constants })

//     console.log('Creating sitemap from files...')

//     const data = await makeSitemap({
//       fileName: inputs.filePath,
//       homepage: baseUrl,
//       distPath: buildDir,
//       exclude: inputs.exclude,
//       prettyURLs: inputs.prettyURLs,
//       changeFreq: inputs.changeFreq,
//       priority: inputs.priority,
//       trailingSlash: inputs.trailingSlash,
//       failBuild: utils.build.failBuild,
//       urlPrefix,
//     })

//     console.log('Sitemap Built!', data.sitemapPath)
//   },
// }